<?php

namespace Dywee\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParametersManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametersManagerRepository extends EntityRepository
{
    /*public function getStockParameters()
    {
        $qb = $this->createQueryBuilder('pm')
            ->select('pm')
            ->where('pm.name like \'%stock%\'');

        return $qb->getQuery()->getResult();
    }*/
}
